### ISSUE TITLE
sendMentoringRequest 500 Internal Server Error

### ISSUE THREAD

**Issue by Kwon770** [JNU-econovation/EggMeet-Server#19]
Error status : 500
Error Message : Internal Server Error

**Comment by Kwon770** [comment]
2022-01-26 21:25:40.468 ERROR 695569 --- [nio-8081-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at com.fivepotato.eggmeetserver.dto.chat.MessageInfoDto.<init>(MessageInfoDto.java:26) ~[classes!/:na]
        at com.fivepotato.eggmeetserver.service.chat.MessageService.createSystemMessage(MessageService.java:51) ~[classes!/:na]
        at com.fivepotato.eggmeetserver.web.chat.StompChatController.sendSystemMessage(StompChatController.java:47) ~[classes!/:na]

**Comment by Kwon770** [comment]
+----+----------------------------+----------------------------+-------------------+------+-------------+-----------+
| id | created_date               | modified_date              | content           | type | chatroom_id | writer_id |
+----+----------------------------+----------------------------+-------------------+------+-------------+-----------+
| 23 | 2022-01-26 21:25:38.905701 | 2022-01-26 21:25:38.905701 | MENTORING_REQUEST |    1 |           2 |      NULL |
| 24 | 2022-01-26 21:25:40.450481 | 2022-01-26 21:25:40.450481 | MENTORING_REQUEST |    1 |           3 |      NULL |
+----+----------------------------+----------------------------+-------------------+------+-------------+-----------+
